name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    timeout-minutes: 5

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Configure NPM
        run: |
          echo "//npm.pkg.github.com/:_authToken=$NPM_TOKEN" > .npmrc
          echo '@saulhardman:registry=https://npm.pkg.github.com' >> .npmrc
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: bahmutov/npm-install@v1

      - run: yarn lint
      - run: yarn build
      - run: yarn test

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
